# 网站标题
title: CCchen's blog
# 网站标题后缀
# suffix:
# 作者名称
author: CC
# 网站关键字
keyword: 技术博客,front-end, javascript, css, html, github, vue
#false是否开启文章背景图显示(随机图片)
is_article_img: true  
# 网站描述
web_description: This is CC's blog, to record my front-end learning journey and daily life.
# 首页文章布局 默认 'card' 可选择 'block-card'
home_layout: card
# 导航名称
menus_title:
  home: HOME
  archive: ARCHIVE
  categories: CATEGORIES
  tags: TAGS
  links: LINKS
  about: ABOUT
# 导航 （不建议修改）
menus:
  home: /
  archive: /archives
  categories: /categories
  tags: /tags
  links: /links
  about: /about
  
# logo
logo: /image/logo.png
# 网页标签上那个小图标 一定要用本地存储
icon: /image/favicon.ico
# 每个页面的展示的图标和一句话
headers:
    home: {
      message: "Hi, I'm CC.",
      icon: /image/logo.png
    }
    archives: {
      # 这里会替换掉两个变量{ year 年，number 总数 } 当然也可以不写这两个变量
      message: "number Articles in year years",
      icon: "https://safesfiles.oss-cn-beijing.aliyuncs.com/safes/ZHNX30835/butterfly_202208301554.png"
    }
    categories: {
      message: "CATEGORIES",
      icon: "https://safesfiles.oss-cn-beijing.aliyuncs.com/safes/ZHNX30835/008-mushroom_202208301554.png"
    }
    tags: {
      message: "TAGS",
      icon: "https://safesfiles.oss-cn-beijing.aliyuncs.com/safes/ZHNX30835/023-watering-can_202208301557.png"
    }
    links: {
      message: "links",
      icon: "https://safesfiles.oss-cn-beijing.aliyuncs.com/safes/ZHNX30835/023-watering-can_202208301557.png"
    }

# 网页访问统计
web_analytics:  
  enable: true #需要改为true
  baidu: 22035a66ebbf23c7f3394ec64cb82f8b  # （替换）百度统计的 Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串
# 评论 
gitalk:
  clientID: 6b93ae26cc4bfe571364 # （需要替换）GitHub Application Client ID.
  clientSecret: 0a421b8d6b87427151ce243a2d804b296e5d3fbf #（需要替换）GitHub Application Client Secret.
  repo: blog-comments-db #（需要替换）GitHub repository.
  owner: plwdxiiu #（需要替换）GitHub repository 所有者，可以是个人或者组织。
  admin: ['plwdxiiu'] #（需要替换）GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。

# 底部显示的图标（github 或者其他）
bottomIcon: 
  #可以多个
  - {
    #描述名称
    name: 'Github',
    #图标    
    iconLink: 'https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imggithub.png',
    #跳转链接    
    toUrl: 'https://github.com/plwdxiiu'
  }
# 友情链接
linksList:
  - {
    title: 'My Github',
    intro: '我的github主页',
    link: 'https://github.com/plwdxiiu',
    image: 'https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imggithub.png'
  }
  - {
    title: 'Onling Tools',
    intro: '在线工具箱',
    link: 'https://tool.lu/',
    image: 'https://safesfiles.oss-cn-beijing.aliyuncs.com/safes/ZHNX30835/042-picnic_202208301620.png'
  }
  - {
    title: 'FE Handbook',
    intro: '前端面试手册',
    link: 'https://www.frontendinterviewhandbook.com/zh/introduction/',
    image: 'https://safesfiles.oss-cn-beijing.aliyuncs.com/safes/ZHNX30835/书_202208301623.png'
  }

#默认的cover (默认缩略图) 在没有填写（这里可以替换（可以是api也可以是固定的图））
default_cover: /image/ladybug.png